"16Rnd_9x21_Mag"
"16Rnd_9x21_Mag"
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"hlc_30rnd_556x45_EPR",
"SmokeShellYellow",
"SmokeShellRed",
"SmokeShellPurple",
"SmokeShellGreen",
"SmokeShellBlue",
"SmokeShellOrange",
"Chemlight_red",
"Chemlight_red",
"Chemlight_red",
"Chemlight_red",
"Chemlight_red",
"Chemlight_yellow",
"Chemlight_yellow",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"B_IR_Grenade",
"Chemlight_red",
"Chemlight_red",
"Chemlight_red",
"Chemlight_red",
"Chemlight_red",
"SmokeShellOrange",
"SmokeShellOrange",
"SmokeShellOrange",
"SmokeShellOrange",
"SmokeShellOrange",
"CUP_PipeBomb_M",
"rhs_mag_m67",
"Chemlight_yellow",


addBackpack "B_AssaultPack_rgr";


